name: Terraform Apply Workflow

on:
  push:
    branches:
      - main   # Trigger the workflow on push to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  terraform:  # Job name
    runs-on: ubuntu-latest  # Runner environment

    steps:  # Steps for the job
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Setup Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0   # Specify your desired Terraform version

    # Step 3: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 4: Select or create workspace
    - name: Select Terraform Workspace
      run: terraform workspace select my-workspace || terraform workspace new my-workspace

    # Step 5: Run Terraform Plan
    - name: Terraform Plan
      run: terraform plan

    # Step 6: Run Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
      
